import Header from "@/components/Header";
import "./globals.css";
import { Archivo, Montserrat } from "next/font/google";
import localFont from "next/font/local";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const helvetica = localFont({
  src: "../../public/fonts/Helvetica_Neue_LT_Std_Black_Condensed_Oblique.otf",
  variable: "--font-helvetica",
});

const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${helvetica.variable} ${archivo.variable} bg-black`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
